name: esy

on: [push, pull_request]

jobs:
  native:
    name: Build for Native

    strategy:
      matrix:
        system: [ubuntu, macos]

    runs-on: ${{ matrix.system }}-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: 14

      - name: Install esy
        run: npm install -g esy

      - name: Create esy wrapper
        run: |
          echo '{
            "name": "build-conf-libsodium",
            "dependencies": {
              "@opam/conf-libsodium": "*"
            },
            "resolutions": {
              "@opam/conf-libsodium": {
                "source": "./libsodium.opam",
                "override": {
                  "dependencies": {
                    "esy-libsodium": "github:EduardoRFS/esy-libsodium#'"${GITHUB_SHA}"'"
                  }
                }
              }
            }
          }' > build.json

      - name: Generate esy lock
        run: esy @build solve

      - uses: esy/github-action@master
        with:
          manifest: ./build.json
          cache-key: ${{ hashFiles('esy.lock/index.json') }}
