name: esy

on: [push, pull_request]

jobs:
  native:
    name: Build for Native

    strategy:
      matrix:
        system: [ubuntu, macos]

    runs-on: ${{ matrix.system }}-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: 14

      - name: Install esy
        run: npm install -g esy

      - name: Create esy wrapper
        run: |
          echo '{
            "name": "build-sodium",
            "dependencies": {
              "@opam/conf-libsodium": "*",
              "@opam/sodium": "*"
            },
            "resolutions": {
              "@opam/conf-libsodium": {
                "source": "./libsodium.opam",
                "override": {
                  "dependencies": {
                    "esy-libsodium": "github:EduardoRFS/esy-libsodium#'"${GITHUB_SHA}"'"
                  }
                }
              },
              "@opam/sodium": "github:EduardoRFS/ocaml-sodium:sodium.json#2d1e2b9b6bc7d92fd27925a0c7795a78d15121cc"
            }
          }' > build.json

      - name: Generate esy lock
        run: esy @build solve

      - uses: esy/github-action@master
        with:
          manifest: ./build.json
          cache-key: ${{ hashFiles('esy.lock/index.json') }}
